name: Deploy Action
description: Action to perform varios deploy operations
inputs:
  vault_password:
    description: Password for opening secrets vault
    required: true
  security_config:
    description: Security config vault
    required: true
  ssh_command:
    description: The SSH command to execute
    required: false
  ansible_playbook:
    description: Name of the Ansible playbook to run
    required: false
  ansible_tags:
    description: Optional Ansible playbook tags
    required: false
  ansible_dry_run:
    description: Indicates if the Ansible playbook run is a test run
    required: false
runs:
  using: composite
  steps:
    - name: Run deploy action
      env:
        IMAGE_VERSION: "2.0"
      shell: bash
      run: |
        docker run \
          --rm \
          --cap-add=NET_ADMIN \
          --workdir /__workspace \
          -v "$GITHUB_WORKSPACE":"/__workspace":ro \
          ghcr.io/anttihuokko/deploy-action:${{ env.IMAGE_VERSION }} \
          --vault-password='${{ inputs.vault_password }}' \
          --security-config='${{ inputs.security_config }}' \
          --ssh-command='${{ inputs.ssh_command }}' \
          --ansible-playbook='${{ inputs.ansible_playbook }}' \
          --ansible-tags='${{ inputs.ansible_tags }}' \
          --ansible-dry-run='${{ inputs.ansible_dry_run }}'
