name: Deploy Action
description: Action to perform varios deploy operations
inputs:
  vault_password:
    description: Password for opening secrets vault
    required: true
  security_config:
    description: Security config vault
    required: true
  ssh_command:
    description: The SSH command to execute
    required: true
runs:
  using: composite
  steps:
    - name: Get image version
      id: version
      shell: bash
      run: echo "VERSION=$(cat version)" >> "$GITHUB_OUTPUT"

    - name: Run deploy action
      shell: bash
      run: |

        echo '---- Version-${{ steps.version.outputs.VERSION }}-'


        docker run \
          --rm \
          --cap-add=NET_ADMIN \
          --workdir /__workspace \
          -v "$GITHUB_WORKSPACE":"/__workspace":ro \
          ghcr.io/anttihuokko/deploy-action:${{ steps.version.outputs.VERSION }} \
          --vault-password='${{ inputs.vault_password }}' \
          --security-config='${{ inputs.security_config }}' \
          --ssh-command='${{ inputs.ssh_command }}'
